Rebol []

dbase: open odbc://patients
port: first dbase

; we are not going to use the NHI as the id but a unique integer
; NHI format is 3 alpha 4 integer

; attempt [insert port {drop table nhilookup}]
insert port ['tables "NHILOOKUP"] ;'
if none? pick port 1 [
    insert port {create table nhilookup ( id integer generated by default as identity primary key, "NHI" CHAR(7) UNIQUE NOT NULL)}
    ; dummy data
    ;insert port {insert into nhilookup (nhi) values ('MZK1240')}
    ;insert port {insert into nhilookup (nhi) values ('abc1234')}
    ;insert port {insert into nhilookup (nhi) values ('efg1923')}

]

;insert port {select * from NHILOOKUP}

;foreach nhis copy port [probe nhis]

; create the clinicians database
; id int surname var 128 fname varchar 128 clintype (1 = doc, 2 = cns) registration int

insert port ['tables "CLINICIANS"] ;'

if none? pick port 1 [
    insert port {create table clinicians ( id integer generated by default as identity primary key, 
        surname varchar(128),
        fname varchar(128),
        clintype int,
        registration int  
    )}
    ; real rheumatology data
    insert port {insert into clinicians ( surname, fname, clintype) values ('Chiu', 'Graham', 1)}
    insert port {insert into clinicians ( surname, fname, clintype) values ('Elasir', 'Haitham', 1)}
    insert port {insert into clinicians ( surname, fname, clintype) values ('Porten', 'Lauren', 2)}
    insert port {insert into clinicians ( surname, fname, clintype) values ('Sawyers', 'Stephen', 1)}
]

; add consults
; id int, clinician id, date timestamp, text blob_e, checksum 

insert port ['tables "letters"] ;'
if none? pick port 1 [
    insert port {
        create table letters (
            id integer generated by default as identity primary key,
            clinicians integer,
            cdate date,
            dictation blob sub_type text,
            checksum char(43)
        )
    }
]

; add patients
insert port ['tables "patients"] ;'
if none? pick port 1 [
    insert port {
        create table patients (
            id integer generated by default as identity primary key,
            created timestamp default current_timestamp,
            nhi integer,
            clinicians integer,
            dob date,
            gender char(1),
            pronoun char(4),
            street varchar(256),
            street2 varchar(256),
            town varchar(256),
            areacode integer,
            email varchar(128),
            phone varchar(15),
            mobile varchar(15),
            gp integer,
            gpcentre integer
        )
    }

]

; vaccination database - where record the vaccines given

insert port ['tables "vaccinations"] ;' 
if none? pick port 1 [
    insert port {
        create table vaccinations (
            id integer generated by default as identity primary key,
            created timestamp default current_timestamp,
            nhi integer,
            vaccineid integer,
            outcome varchar(128),
            vaxdate date
        )    
    }
]

; GP medical centres

insert port ['tables "gpcentre"] ;'
if none? pick port 1 [
    insert port {
        create table gpcentre (
            id integer generated by default as identity primary key,
            centrename varchar(128),
            street varchar(128),
            street2 varchar(128),
            town varchar(128),
            city varchar(128),
            phone varchar(15),
            fax varchar(15),
            email varchar(128),
            edi varchar(128)
        )
    }
]

; vaccines which we use
insert port ['tables "vaccines"] ;' eg. pfizer/biontech covid-19
if none? pick port 1 [
    insert port {
        create table vaccines (
            id integer generated by default as identity primary key,
            created timestamp default current_timestamp,
            name varchar(128),
            vaxdate date
        )    
    }
]

close port
